### ISSUE TITLE
Provide a way to ensure the index-store already sync to the tip

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/ckb-cli#199]
We need to ensure the index-store already synchronizes to the tip in some of the scenes, e.g. query the capacity, transfer a new cell to others.

* One style is that add an argument `--wait-for-sync=true` for commands like `wallet get-capacity`, `wallet transfer`, `dao deposit`.
* One style is that add a sub-commands, like `util wait-for-sync --number=[number] | tip`, to wait for the index-store synchronizes to `number` or `tip`.

I prefer the first one.

**Comment by TheWaWaR** [comment]
I prefer the first one too.

I think `util wait-for-sync --number=[number]` is meaning less, seems no use case for it.
