### ISSUE TITLE
ckb-sdk：TxHelper need a function to reorder input cell by input group

### ISSUE THREAD

**Issue by driftluo** [nervosnetwork/ckb-cli#215]
Reorder input cell by input group will reduce transaction size, because it wll reduces witnesses size.

- For inputs [g1, g2, g1], we need 2 witnesses [witness1, witness2].
- For inputs [g1, g2, g1, g3], we need 4 witnesses includes an empty bytes to align witness3 for g3 [witness1, witness2, (empty bytes), witness3].
- For inputs [g1, g2, g2, g1], we need witnesses [witness1, witness2].
- For inputs [g1, g1, g1, g1], we need witnesses [witness1].

**Comment by TheWaWaR** [comment]
It's a trivial optimization, will do it later.
