### ISSUE TITLE
`output_index` is duplicated to `LiveCellInfo::index`

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/ckb-cli#218]
[`LiveCellInfo::tx_index`](https://github.com/nervosnetwork/ckb-cli/blob/develop/ckb-index/src/index/types.rs#L581) is duplicated to [`LiveCellInfo::index`](https://github.com/nervosnetwork/ckb-cli/blob/develop/ckb-index/src/index/types.rs#L591) which already contains `tx_index` and `output_index`.

Changing to `LiveCellInfo` will introduce the incompatibility of storage. So we do this small change once we decide to make an incompatible update.

**Comment by doitian** [comment]
Cli should be able to migrate the database schema, refer to how ckb implement it.
