### ISSUE TITLE
Virtual workspace root and [patch]

### ISSUE THREAD

**Issue by Ericson2314** [nervosnetwork/ckb-cli#243]
Have you all considered using a non-package virtual workspace root (https://doc.rust-lang.org/cargo/reference/manifest.html#virtual-manifest) along with the `[patch]` section? It makes it easier to not repeat patch dependencies or overrides of crates.io dependencies in each crate.

**Comment by doitian** [comment]
The issue is stalled for a long time. We don't have the requirement to do the patch locally, so it's not planned to change it. However, pull request is welcome.
