### ISSUE TITLE
ckb-cli server wasn't expected?

### ISSUE THREAD

**Issue by wwaayyaa** [nervosnetwork/ckb-cli#255]
![image](https://user-images.githubusercontent.com/6279538/76829698-b6203500-685e-11ea-91d9-8ef6f98b0264.png)

**Comment by wwaayyaa** [comment]
[docs](https://github.com/nervosnetwork/ckb-cli/blob/develop/docs/API-Server.md)

**Comment by TheWaWaR** [comment]
The `server` sub-command is included in later version of `ckb-cli`, you may need build by yourself by:

``` shell
git clone https://github.com/nervosnetwork/ckb-cli.git
cd ckb-cli
make prod
```

**Comment by wwaayyaa** [comment]
thanks
