### ISSUE TITLE
Mining with CKB-Cli (for dev chain)

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#259]
When we have to send a series of transactions to implement a complete feature, we can't control the speed of producing blocks, so we can't test the cases with boundary conditions.

For example:
When we develop a dApp in CKB, we construct a transaction `tx1`, send it to dev chain, then wait a block to package it.
And we want to test what will happen if another transaction `tx2` was packaged in the next block.

It's a bit complex:
1. Start a dev chain.
2. Start a miner and set a bigger delay time.
3. Send `tx1`.
4. Construct `tx2` as quick as we can.
5. Try send `tx2` before the next block was produced.

But, if `ckb-cli` can mine blocks, we can do it easier.

The pseudo steps are as follow:
```
miner.start()
// do something that don't care the height
miner.stop()
send(tx1)
miner.mine(1)
send(tx2)
// check the result of tx2
miner.start()
```

**Comment by TheWaWaR** [comment]
Sounds a good feature implement in `ckb-cli`. Simple but useful.

**Comment by doitian** [comment]
ping @driftluo @xxuejie @jjyr

**Comment by doitian** [comment]
In Dummy mode, existing CKB RPC for miner is enough to create blocks on demand
