### ISSUE TITLE
Help wanted:  Err : TokioCoreError("Unable to create") 

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/ckb-cli#269]
Running ckb-cli  (2a7ed95) on MacOS 10.15.4 and get this error:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:   
Error(TokioCoreError("Unable to create"), State { next_error: Some(Os { code: 24, kind: Other,   
message: "Too many open files" }), backtrace: InternalBacktrace { backtrace: None } })',   
src/libcore/result.rs:1188:5
```
Backtrace as follow:  
>   1: backtrace::capture::Backtrace::new_unresolved
   2: error_chain::backtrace::imp::InternalBacktrace::new
   3: <core::result::Result<T,E> as jsonrpc_client_http::ResultExt<T>>::chain_err
   4: jsonrpc_client_http::create_standalone_core
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::panicking::try::do_call
   7: __rust_maybe_catch_panic
   8: core::ops::function::FnOnce::call_once{{vtable.shim}}
   9: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  10: std::sys::unix::thread::Thread::new::thread_start
  11: _pthread_start
) } })', src/libcore/result.rs:1188:5
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: ckb_sdk::rpc::client::RawRpcClient<jsonrpc_client_http::HttpHandle>::from_uri
  10: ckb_cli::interactive::InteractiveEnv::from_config
  11: ckb_cli::main
  12: std::rt::lang_start::{{closure}}
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
  15: std::rt::lang_start_internal
  16: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

Are there any way to fix this error?

**Comment by TheWaWaR** [comment]
It says "Too many open files", please check your `ulimit` settings.

**Comment by timfaner** [comment]
It works, thank you. BTW, it's wired that in version 0.28.0 I didn't encountered this problem.
