### ISSUE TITLE
Mock-tx for lock script verify failed when ckb-standalone-debugger succeed 

### ISSUE THREAD

**Issue by timfaner** [nervosnetwork/ckb-cli#271]
Recently I'm developing a [script](https://github.com/cryptape/ckb-crypto-demo/blob/6f105d85d251715feae9a8bae234cec25c5e397e/src/blsverify.c) which aims at unlock tx using BLS signature . The script validated successfully using [ckb-standalone-debugger](https://github.com/xxuejie/ckb-standalone-debugger),  consumed *3429643889* cycles.  When trying verify script by using `ckb-cli mock-tx verify` , script _do not_ exit normally, instead script execute again and finally failed , throw 
``` shell
Error { kind: InternalError { kind: Compat { error: ErrorMessage { msg: "InvalidEcall(57)" } }
```
I don't know where is the problem, can you help me ?

#### Screen shot
<img width="1785" alt="截屏2020-04-10 下午12 18 40" src="https://user-images.githubusercontent.com/15355789/78962816-e2f6fd80-7b27-11ea-94bf-8ae3bbeb3903.png">

#### script binary and mocked-tx.json
[blsverify.zip](https://github.com/cryptape/ckb-crypto/files/4459898/blsverify.zip)

**Comment by TheWaWaR** [comment]
It's an error message from `ckb-vm`, seems there is something wrong with your binary. As I understand `ecall` code (syscall) only allow value with:
* `93` : [exit](https://github.com/nervosnetwork/ckb-vm/blob/416bb211abea1ef79ffa5ce3b14706044e65cd2a/src/machine/mod.rs#L322-L326)
* `syscalls`: [syscall](https://github.com/nervosnetwork/ckb/blob/15b652b487452c5a8c23bf8fbd6129f2a2dd126c/script/src/syscalls/mod.rs#L33-L46)

`57` is an invalid ecall code. @xxuejie

**Comment by timfaner** [comment]
Some typos in tx file caused the problem,  have nothing todo with ckb-cli
