### ISSUE TITLE
The command line mode has no warning message about the out-dated index

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-cli#281]
<details><summary>Chat log from Telegram</summary>

<pre><code>Kenny Bambridge, [May 18, 2020 at 7:40:51 AM]:
ckb-cli wallet get-capacity --address ckt1**wgna
total: 0.0 (CKB)

thats what it outputs

but thats what it shows in ckb studio

Matt Quinn, [May 18, 2020 at 7:41:40 AM]:
does the balance for the other address come back correct?

Kenny Bambridge, [May 18, 2020 at 7:41:45 AM]:
no

ckb-cli just doesn't seem to output it correctly

Matt Quinn, [May 18, 2020 at 7:42:06 AM]:
can you check if the block fields are matching up?

like latest block?

Kenny Bambridge, [May 18, 2020 at 7:48:25 AM]:
yep they match closely

20978

20984

it just updates every 5s

Kenny Bambridge, [May 18, 2020 at 7:50:16 AM]:
so I can see the two transactions from ckb-cli: ckb-cli 
rpc get_transactions_by_lock_hash --hash 0x2b0f**366419 --page 0
- created_by:
    block_number: 20593
    tx_hash: 0x5930e**13516c
    index: 0
  consumed_by: ~
- created_by:
    block_number: 20659
    tx_hash: 0x3f833**4c08
    index: 0
  consumed_by: ~

I sent two transactions with 20000 ckb

transaction:
  version: 0
  cell_deps:
    - out_point:
        tx_hash: 0xace5**13058555b708
        index: 0
      dep_type: dep_group
  header_deps: []
  inputs:
    ...
  outputs:
    - capacity: "20090.0"
      lock:
        code_hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 (sighash)
        args: 0x2fa3c***b7249
        hash_type: type
      type: ~
  outputs_data:
    - 0x
  witnesses:
    ...
  hash: 0x3f833d***2f7464c08
tx_status:
  status: committed
  block_hash: 0x41fd***e1e3aa03cd4

Kenny Bambridge, [May 18, 2020 at 7:53:36 AM]:
^ proof that it actually sent 20009 ckb

I think something is wrong with the get-capacity function in ckb-cli

Kenny Bambridge, [May 18, 2020 at 8:03:55 AM]:
Okay @MattQuinn I found the issue...

I didn't run ckb-cli server

the command should probably warn you if that's not running

all it does is report 0 CKB LOL

ian, [May 18, 2020 at 8:16:30 AM]:
I think that's not the reason. CKb-cli will synchronize data from the node and build its own index. The command line option --wait-for-sync tells ckb-cli to block until the index is up-to-dated. Ckb-cli needs to run in the background to build the index, the interactive mode and ckb-cli server will do the trick. I believe in the interactive mode, ckb-cli does throw warning when the index is not ready yet, it seems that such warning is absent in command line mode.</code></pre>

</details>

**Comment by doitian** [comment]
<details><summary>More about the scenario</summary>
<pre><code>Kenny Bambridge, [May 18, 2020 at 8:22:07 AM]:
I decided to only delete the data in genesis hash for my currently running network: main INFO main  chain genesis hash: 0x823b2ff5785b12da8b1363cac9a5cbe566d8b715a4311441b119c39a0367488c

and that worked

so basically ckb-cli thought it was further ahead since my other network had mined more blocks, but it probably had the same genesis hash

because it was the default ckb init --chain dev</code></pre></details>

**Comment by TheWaWaR** [comment]
Oops, It should reject the sub-commands which need indexing. I'll check it out soon.

**Comment by doitian** [comment]
See the first comment, cli may believe it already has the latest index.

**Comment by TheWaWaR** [comment]
It's may behave that way by design. So that user do not have to wait for index database to sync to tip to:
1. transfer some old live cells to some address
2. query some old live cells to use

I think what we missing here is to tell user the indexing process when it's not sync to tip.
