### ISSUE TITLE
Use an argument or an environment variable to control the data directory

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#283]
When I want to start more than one `ckb` instances and execute more than one `ckb-cli` commands in parallel, I want to use different data directories.

For example, run some tests in parallel.

**Comment by TheWaWaR** [comment]
Already in included in https://github.com/nervosnetwork/ckb-cli/pull/249

https://github.com/nervosnetwork/ckb-cli/pull/249/commits/698b2839396aac946fa1501070f07b7999e66588#diff-639fbc4ef05b315af92b4d836c31b023R59

**Comment by yangby-cryptape** [comment]
> Already in included in #249
> 
> [698b283#diff-639fbc4ef05b315af92b4d836c31b023R59](https://github.com/nervosnetwork/ckb-cli/commit/698b2839396aac946fa1501070f07b7999e66588#diff-639fbc4ef05b315af92b4d836c31b023R59)

When I execute `ckb-cli`, the directory `${HOME}/.ckb-cli` is created automaticlly.
But why when I execute `ckb-cli` with `CKB_CLI_DIR`, it throws an error when directory is not existed.

**Comment by yangby-cryptape** [comment]
Since that commit hasn't been merged, you still can update it: maybe the name "CKB_CLI_HOME" is better.

**Comment by TheWaWaR** [comment]
> Since that commit hasn't been merged, you still can update it: maybe the name "CKB_CLI_HOME" is better.

Sounds good to me.
