### ISSUE TITLE
Request more features for subcommands

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#285]
- [ ] I didn't find a way to input witness via `ckb-cli tx`.
  I want to use `ckb-cli` in bash script, so I don't want to edit the `tx-file` manually.
- [ ] Export private key as hex plain text via `ckb-cli account`.

**Comment by Kuzirashi** [comment]
Does:
```
ckb-cli ccount export --lock-arg 0x580b4eecfe76456dd835d844e404645bb91a8fac --extended-privkey-path pk.txt
```

help with exporting private key part?
