### ISSUE TITLE
Return `ok` for no-outputs commands is terrible

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#286]
#### Some commands return `ok` when do successful execution

For example:
- `ckb-cli tx init`
- `ckb-cli tx add-input`
- `ckb-cli tx add-output`
- `ckb-cli tx sign-inputs`

#### Why it is terrible

- The `ok` is not `YAML` or `JSON` format, so it means `--output-format < json | yaml >` doesn't work for these commands.
  For example, `ckb-cli tx send` returns `TX_HASH` without `--output-format` and it returns `"TX_HASH"` with `--output-format json`.
  So I can't define a function to wrap `ckb-cli --output-format json` to use json format to parse outputs.
  If I have to add parsing statements after each `ckb-cli` commands, **it is terrible**.
  In current, I have to write code like this (pseudo code):
  ```
  def call_ckb_cli(args):
      let (return_code, output) = execute("ckb-cli", "--output-format", "json", args)
      if return_code != 0:
          return Err(())
      if output == "ok":
          return Ok(JSON::null())
      else
          return Ok(JSON::new(output))
  ```
- Sometimes `ckb-cli` returns data and sometimes it returns executing states.
  It's disunity.
- When using `ckb-cli` in bash, the result can be checked with the return code. But I have to add `>/dev/null` for some `ckb-cli` commands when I want to redirect the outputs.
   I have to remember which returns executing states and which returns data, **it is terrible**.

#### Suggestions

I think there are few solutions:
- Add `--quiet` argument.
- **(I prefer to this)** Returns "ok" when use `--verbose`.
- **(and this)** Output `ok` to `stderr`.
- Output nothing for these commands.

**Comment by TheWaWaR** [comment]
I prefer "Add `--quiet` argument". 

Or output something like (yaml):
```yaml
result: success
```

**Comment by yangby-cryptape** [comment]
> I prefer "Add `--quiet` argument".
> 
> Or output something like (yaml):
> 
> ```yaml
> result: success
> ```

Same issue: half commands return only data and half commands return only executing states.

**Comment by doitian** [comment]
I think we can serialize `Result<A, B>` into:

```
{ "success": true, "result": A }
```

or

```
{ "success": false, "error": B }
```

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/ckb-cli/pull/309
