### ISSUE TITLE
The `stdout` output is not well formed when `--debug` enabled

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#288]
Perhaps `ckb-cli` can output all debug messages into `stderr` or a file under `.ckb-cli`?

Associated Issues: #286 and #287.

**Comment by TheWaWaR** [comment]
Agreed, this way can have better user experience.

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/ckb-cli/pull/309
