### ISSUE TITLE
Should the `--wait-for-sync` option be enabled defaultly?

### ISSUE THREAD

**Issue by jjyr** [nervosnetwork/ckb-cli#292]
Suggestion:

* Make `wait-for-sync` default enabled.
* Provides a negative option `--no-sync` to disable `wait-for-sync`.

Reasons:

* User expect the correct result, but without the option, ckb-cli often returns the unexpected result, which confuses users.
* Mostly subcommand depend on the `index` state, which often can't work properly if `index` is lack of syncing.
* We should make the program safe and usable default.

**Comment by TheWaWaR** [comment]
Related issue #290 

I agree with you, `wait-for-sync` do lend unsafe results. However user may don't want sync to tip when he/she can make sure the result is expected, `--no-sync` is a good solution.
