### ISSUE TITLE
Feature Request: Show testnet addresses with `account bip44-addresses`

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#305]
`account bip44-addresses` is a useful subcommand for showing change and receiving addresses with their derivation path, but it only shows mainnet addresses. It would be great if you could pass an optional `--network` argument which defaults to `mainnet` but also accepts `testnet` to show `ckt...` addresses.

Current behavior was confirmed as of `856af0b8a29043f36f06d4f5be7744a293ae24d2`. Thanks!

**Comment by TheWaWaR** [comment]
Agreed.
