### ISSUE TITLE
`tx sign-inputs` does not take sighash address as an option (on testnet)

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#315]
Tested on `b2c35a486ec766008acfea778a4d33c87acf2724`

It seems either the --help command is incorrect, there is a bug when trying to use a sighash address in `--from-account`, or testnet addresses are not supported. The --help states sighash addresses should work:

```
        --from-account <from-account>    The account's lock-arg or sighash address (transfer from this account)
```

But if you try to use one as the `--from-account`, the operation results in a parse failure:

```
CKB> tx sign-inputs --from-account ckt1qyqv8256ceslzzp72rxfz5wutpsfk35jzdasfwd9fd --tx-file tx.json
parse hex string failed: Invalid character
```

Switching to the account's lock-arg will work, however:
```
CKB> tx sign-inputs --from-account 0x3e2ad665a2cb4696d3fc4a217047dd25e30d73cd --tx-file tx.json
Password:
- lock-arg: 0x3e2ad665a2cb4696d3fc4a217047dd25e30d73cd
  signature: 0x3c37421080ad3c3e5a9488acbb2cd84806a33e273388b255495d118edc87df85095aa37af7518fd20896884722f632cd1923a7180440bcfa4724686de32c06f501
```

Thanks in advance!

**Comment by TheWaWaR** [comment]
Fixed in https://github.com/nervosnetwork/ckb-cli/pull/336
