### ISSUE TITLE
After installing plugin the default keystore does not work due to missing password

### ISSUE THREAD

**Issue by dfordivam** [nervosnetwork/ckb-cli#325]
If a plugin is installed which does not need a password, the `ckb-cli` does not prompt for password for the default keystore.
So most of the commands stop working for the default keystore account.

The logic of this API should be fixed to decide the password requirement based on the keystore being used (default or plugin)

https://github.com/nervosnetwork/ckb-cli/blob/66224435e14ade866b202d5002619e2f08e37d09/src/plugin/manager.rs#L227-L231

**Comment by TheWaWaR** [comment]
https://github.com/nervosnetwork/ckb-cli/blob/bb75209342706e8c4ead1cf75a7684e7be6d1628/src/plugin/manager.rs#L1390-L1399
It will actually try to read password when the error message from builtin keystore is `keystore require password`

The mistake is some cases not covered. 

https://github.com/nervosnetwork/ckb-cli/blob/develop/src/plugin/builtin.rs#L46
