### ISSUE TITLE
Default path for hardware wallets must include the chain code

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#328]
The default path currently used by CKB-CLI cannot be used for hardware wallets. I recommend the default path `m/44'/309'/0'` for hardware wallets instead.

This issue can be circumvented over the command line through the `--path` command, but improving the default makes the most sense.

Impacted subcommands include (but may not be limited to)
- `account extended-address`
- `wallet transfer`
- `dao deposit`,` dao prepare`, `dao withdraw`
- `util sign-data`, `util sign-hash`
- `tx sign-inputs`

**Comment by TheWaWaR** [comment]
You are right. Will fix this as soon as possible.
