### ISSUE TITLE
Plugin System: WitnessArgs are not provided in the SignTarget Object

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#330]
The Ledger plugin (and thus Ledger device/app) is not receiving witness args in a multi-sig context from the plugin system. As a result, multisig operations cannot currently be signed by the Ledger app.

The Ledger app needs the witness args, which can be provided before signing by leaving the signatures zeroed out.

Here is a patch we applied to our fork to address this, use as much of it as you like! https://github.com/obsidiansystems/ckb-cli/commit/6b1c4dca0c7f92b7f61d8cab7531cfc3c441e446

**Comment by TheWaWaR** [comment]
Will be fixed soon.
