### ISSUE TITLE
can not export  `Export master private key and chain code as hex plain text`

### ISSUE THREAD

**Issue by GQQQy** [nervosnetwork/ckb-cli#339]
I have used the `account export --lock-arg 0xcafebabe  --extended-privkey-path (my path)` cmd
```
﻿﻿Password: ...
File exists: mypath
```
but in mypath there is nothing

**Comment by TheWaWaR** [comment]
It says `File exists`, means if the file exists whether it is empty or not. The solution is remove or rename the file (which is `mypath` in your case) first.

**Comment by GQQQy** [comment]
> It says `File exists`, means if the file exists whether it is empty or not the command can not proceed. The solution is remove or rename the file (which is `mypath` in your case) first.

oh, I have checked the path, and there is nothing... so I choose to use ckb-studio
