### ISSUE TITLE
Missing line terminators in some help messages

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb-cli#352]
For example: `ckb-cli -V` & `ckb-cli --version`.

This bug is only in `clap=3.0.0-beta.1`. Both of `2.33.3` and ` 3.0.0-beta.2` are ok.

Perhaps, you shouldn't use a beta version of `clap`.
I suggest that use `2.33.3` to instead of.

**Comment by doitian** [comment]
See why using the beta version in this thread: https://github.com/nervosnetwork/ckb-cli/pull/225/files#r363621551

**Comment by TheWaWaR** [comment]
Clap will be updated when clap reached at least an release candidate version.
