### ISSUE TITLE
Failed to withdraw from DAO

### ISSUE THREAD

**Issue by xiaoxq** [nervosnetwork/ckb-cli#390]
I deposited all CKB to DAO and left 0 balance in account. Now I want to withdraw but it keeps failing with
`Capacity not enough: ckb... => 0`

So the tx-fee has to be paid by the main account, right?

**Comment by TheWaWaR** [comment]
Yes. You can read the [Deposit and Withdraw in Nervos DAO](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md) RFC for more information.
