### ISSUE TITLE
Missing newline after printing version.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-cli#417]
There is no newline after printing the version. Please see the screenshot below for comparison with the CKB node and CKB Indexer.

![20210824002132](https://user-images.githubusercontent.com/37931/130574334-8077ec1d-bf62-4980-91b6-4d6565b88eb5.png)

**Comment by TheWaWaR** [comment]
Good catch.

**Comment by TheWaWaR** [comment]
Will fix in PRhttps://github.com/nervosnetwork/ckb-cli/pull/418
