### ISSUE TITLE
ckb-cli does not support `data1` and future hash type variants when printing hash type on screen

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-cli#463]
1. https://github.com/nervosnetwork/ckb-cli/blob/163ed210f526b69a1f957bbf17a31e05defb3182/ckb-sdk/src/tx_helper.rs#L501-L505
2. https://github.com/nervosnetwork/ckb-cli/blob/163ed210f526b69a1f957bbf17a31e05defb3182/ckb-sdk/src/types/address.rs#L190-L194

**Comment by TheWaWaR** [comment]
* Case 1 is a bug
* Case 2 will be fixed in PR #461

**Comment by TheWaWaR** [comment]
Close the issue since above fix PR all merged.
