### ISSUE TITLE
ckb-cli open too many threads

### ISSUE THREAD

**Issue by jjyr** [nervosnetwork/ckb-cli#47]
![IMAGE 2019-08-15 01:32:13](https://user-images.githubusercontent.com/1695400/63042404-82fa7980-befc-11e9-83ea-e7f87503bffa.jpg)

Number of threads jumps crazy after the two steps.

1. Open the interactive mode and leave.
2. shutdown the ckb node.

Seems like the index threads hangs.

**Comment by TheWaWaR** [comment]
Seems also have related memory leak issue.
