### ISSUE TITLE
error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Xcodes-chain** [nervosnetwork/ckb-cli#534]
I have a problem here：

env:MacOS ARM64
version:ckb-cli 1.4.0
api url:https://testnet.ckbapp.dev/

Case:
How to reproduce:
     1.  build and generate ckb-cli tool
     2. export an env
     3. execute the prepared command according to the [wiki](https://github.com/nervosnetwork/ckb-cli/wiki/Deploy-contracts)
     4. run the command to generate a transaction for deploying the contract
     5. error:No such file or directory (os error 2)
 
ScreenShot:
    1.  run the command 
<img width="844" alt="image" src="https://user-images.githubusercontent.com/45781590/212874449-89d18570-edc9-4483-bb31-7bc772f474c9.png">

**Comment by 15168316096** [comment]
Temporary solution:
    1. use this project to complete the generate deployment contract transaction, git clone git@github.com:mohanson/ckb-playground.git && cd contract_deploy/
    2. re-apply for a ckb account and ckb funds and then you need to delete the original json in your migration directory
    3. run the command: 
```
ckb-cli deploy gen-txs \
  --deployment-config ./deployment.toml \
  --migration-dir ./migrations \
  --from-address ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdrcaufs8qeu8wvvy0myyedek4vqad9qeq3gc4cf\
  --info-file ./test.json
```
    4. screenshot:
![image](https://user-images.githubusercontent.com/45781590/213075935-38a82d9f-d766-46ab-9c37-e05e6825735a.png)

**Comment by 15168316096** [comment]
Sign and Send the deploy transaction:
    1. sign tx:
```
ckb-cli deploy sign-txs --from-account ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdrcaufs8qeu8wvvy0myyedek4vqad9qeq3gc4cf \
--add-signatures \
--info-file ./test.json
```
    2. send tx:
` ckb-cli deploy apply-txs --info-file ./test.json --migration-dir ./migrations`
    3. Find this transaction in the blockchain [explore](https://pudge.explorer.nervos.org/transaction/0xd7c7da36e9200d3e91f2fdb702e94d2b6f58f67d9fc1fbef417c8f4a39d96d74)
