### ISSUE TITLE
Releases do not contain Apple Silicon binary of ckb-cli

### ISSUE THREAD

**Issue by serejke** [nervosnetwork/ckb-cli#539]
Could you also build and release M1/M2 `ckb-cli`?

**Comment by quake** [comment]
the x86 binary can run with rosetta

**Comment by zhangsoledad** [comment]
The binary for the arm architecture is not available at the moment, but you can currently run x86_64-apple-darwin via rosetta instead.

```bash
softwareupdate --install-rosetta --agree-to-license
arch -x86_64 ./ckb-cli
```

**Comment by zhangsoledad** [comment]
Apple Silicon binary is now available
