### ISSUE TITLE
Compatibility issue with Ledger

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/ckb-cli#542]
**CKB Cli** is expected to be able to work with Ledger via **ckb-plugin-ledger**, but the plugin was declared out-of-date by @TheWaWaR, also confirmed by user @191855 (https://github.com/nervosnetwork/neuron/issues/2583#issuecomment-1418268986). An update on ckb-plugin-ledger is desired to re-enable this feature.

PS: This issue is opened here instead of https://github.com/obsidiansystems/ckb-plugin-ledger for better tracking, suggested by @quake

**Comment by Keith-CY** [comment]
Hi there, ckb-cli is the default signer of [Kuai](https://github.com/ckb-js/kuai/) to deploy contracts.

Now we are going to support ledger for contract deployment, so I wonder if there's a plan to fix the compatibility issue.

If there's such a plan, we will add ledger support in Lumos first.

**Comment by 15168316096** [comment]
I tried to compile the ckb-plugin-ledger project using both cargo build and nix-build and found that the required version of the ckb-cli is too old, leading to compilation failures.

```
nix-build:

vbnet
Copy code
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to get `ckb-cli-plugin-protocol` as a dependency of package `ckb-plugin-ledger v0.2.1 (/build/source)`

Caused by:
  failed to load source for dependency `ckb-cli-plugin-protocol`

Caused by:
  Unable to update https://github.com/nervosnetwork/ckb-cli?rev=babc52ae593474f7fddb80f7c229374203310d6a#babc52ae

Caused by:
  object not found - no match for id (babc52ae593474f7fddb80f7c229374203310d6a); class=Odb (9); code=NotFound (-3)
...
```
```
cargo build:

vbnet
Copy code
error: failed to get ckb-cli-plugin-protocol as a dependency of package ckb-plugin-ledger v0.2.1 (/workspace/ckb-plugin-ledger)

Caused by:
  failed to load source for dependency ckb-cli-plugin-protocol

Caused by:
  Unable to update https://github.com/nervosnetwork/ckb-cli?rev=babc52ae593474f7fddb80f7c229374203310d6a#babc52ae

Caused by:
  object not found - no match for id (babc52ae593474f7fddb80f7c229374203310d6a); class=Odb (9); code=NotFound (-3)
```
Afterward, I attempted to use the same Cargo.toml as ckb-cli, and I found that some internal implementations in ckb-plugin-ledger need to be adapted to the new development dependencies.

**Comment by TheWaWaR** [comment]
I think maybe the branch of committed id belong to already deleted, but the commit can browser in github page. You can try clone the repo and checkout the commit and push a special branch in you forked repo. Then you reference the commit id in your repo, it might works.

**Comment by Keith-CY** [comment]
Hi @15168316096 @TheWaWaR Any update on the plugin?

**Comment by TheWaWaR** [comment]
> Hi @15168316096 @TheWaWaR Any update on the plugin?

I have no idea, please contact the current maintainer.

**Comment by doitian** [comment]
@code-monad said he will take a look at this problem

**Comment by code-monad** [comment]
I've made changes that makes this repo compiles without error. Need some testing tho. Trying to test with my handing ledge nano s now.

**Comment by code-monad** [comment]
update: it is recommended to move to cryptape's fork: https://github.com/cryptape/ckb-plugin-ledger since the original repo is inactive, and we'll take over the maintenance work

**Comment by Keith-CY** [comment]
> update: it is recommended to move to cryptape's fork: [cryptape/ckb-plugin-ledger](https://github.com/cryptape/ckb-plugin-ledger) since the original repo is inactive, and we'll take over the maintenance work

Issues are open open in repo https://github.com/cryptape/ckb-plugin-ledger
