### ISSUE TITLE
Integration test is not stable

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-cli#553]
I saw a lot of integtation test failures like this:

```
[2023-05-10T03:48:48Z INFO  ckb_cli_test::miner] mine until tx: balance capacity error: `transaction dependency provider error: `invalid cell status: "unknown"``

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid format, expected a 0x-prefixed hex string with 64 digits", line: 1, column: 88)', src/miner.rs:124:79
stack backtrace:
```

**Comment by liuck8080** [comment]
This PR also fix integration test: https://github.com/nervosnetwork/ckb-cli/pull/554

**Comment by eval-exec** [comment]
`DaoPrepareMultiple` is [unstable](https://github.com/nervosnetwork/ckb-cli/actions/runs/5420726369/jobs/9857018733) too:
<details>
<pre>
[2023-06-30T09:52:48Z INFO  ckb_cli_test] ==================== DaoPrepareMultiple ====================

[2023-06-30T09:52:48Z INFO  ckb_cli_test::util] [Execute]: /home/runner/work/ckb-cli/ckb-cli-integration/ckb_v0.108.0_x86_64-unknown-linux-gnu/ckb "-C /tmp/.tmpjUXxnp init --chain dev --rpc-port 8000 --p2p-port 8100"
[2023-06-30T09:52:48Z INFO  ckb_cli_test::setup] run ckb: "/home/runner/work/ckb-cli/ckb-cli-integration/ckb_v0.108.0_x86_64-unknown-linux-gnu/ckb" "-C" "/tmp/.tmpjUXxnp" "run" "--indexer" "--ba-advanced"
[2023-06-30T09:52:51Z INFO  ckb_cli_test::setup] [Execute]: dao query-deposited-cells --address ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37
[2023-06-30T09:52:52Z INFO  ckb_cli_test::setup] [Execute]: dao query-prepared-cells --address ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37
[2023-06-30T09:52:53Z INFO  ckb_cli_test::setup] [Execute]: dao deposit --fee-rate 1000 --capacity 102 --privkey-path /tmp/.tmpdaz2a3/pk
[2023-06-30T09:52:53Z INFO  ckb_cli_test::miner] mine until tx: 0xe27877ba271b06c3f1440712caf56cfe0200c960f112653955582f72b77ce389
[2023-06-30T09:52:54Z INFO  ckb_cli_test::setup] [Execute]: dao deposit --fee-rate 1000 --capacity 102 --privkey-path /tmp/.tmpdaz2a3/pk
[2023-06-30T09:52:55Z INFO  ckb_cli_test::miner] mine until tx: 0x28424efbe67b2acf27e4fd7df69931f48ffd75bb48bad721f68c5e7b3d556c74
[2023-06-30T09:52:55Z INFO  ckb_cli_test::setup] [Execute]: dao deposit --fee-rate 1000 --capacity 400000 --privkey-path /tmp/.tmpdaz2a3/pk
[2023-06-30T09:52:55Z INFO  ckb_cli_test::miner] mine until tx: 0xe458a04f365300397f8f849146a68040ac69f29f34d293ea4ae6b8f6889bd55b
[2023-06-30T09:52:56Z INFO  ckb_cli_test::setup] [Execute]: dao query-deposited-cells --address ckt1qyqvsv5240xeh85wvnau2eky8pwrhh4jr8ts8vyj37
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `20400000000`,
 right: `40020400000000`', src/spec/dao.rs:69:9
stack backtrace:
   0:     0x558ecaa338da - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x558ecaa338da - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558ecaa338da - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x558ecaa338da - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x558ecaa5b08e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x558ecaa2d875 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x558ecaa336a5 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x558ecaa336a5 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x558ecaa3502f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x558ecaa34d6b - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x558ecaa3573c - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x558ecaa354d9 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x558ecaa33d8c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x558ecaa351e2 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x558ec9c5c583 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x558ec9c5c89f - core::panicking::assert_failed_inner::h44cce2dcc2552f50
  16:     0x558eca55fdea - core::panicking::assert_failed::h45485f7dd8b7dc56
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:199:5
  17:     0x558ec9cba0a0 - <ckb_cli_test::spec::dao::DaoPrepareMultiple as ckb_cli_test::spec::Spec>::run::h701aba60644d164d
                               at /home/runner/work/ckb-cli/ckb-cli/test/src/spec/dao.rs:69:9
  18:     0x558ec9cc6983 - ckb_cli_test::run_spec::hda3a7114bc0b54e3
                               at /home/runner/work/ckb-cli/ckb-cli/test/src/main.rs:68:5
  19:     0x558ec9cc60ac - ckb_cli_test::main::hca0ca05185395816
                               at /home/runner/work/ckb-cli/ckb-cli/test/src/main.rs:32:9
  20:     0x558ec9c7f68b - core::ops::function::FnOnce::call_once::ha310a8f19985a8a8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:507:5
  21:     0x558ec9c9c61e - std::sys_common::backtrace::__rust_begin_short_backtrace::h7e956293f72ffd6c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:121:18
  22:     0x558ec9c97b51 - std::rt::lang_start::{{closure}}::h0462a1e94386239f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:166:18
  23:     0x558ecaa280bc - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
  24:     0x558ecaa280bc - std::panicking::try::do_call::h0497133ebe1341e5
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  25:     0x558ecaa280bc - std::panicking::try::h6c3de05c7ca5d07f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  26:     0x558ecaa280bc - std::panic::catch_unwind::h969058ecb5334b30
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  27:     0x558ecaa280bc - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
  28:     0x558ecaa280bc - std::panicking::try::do_call::h77301dcf43953993
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
  29:     0x558ecaa280bc - std::panicking::try::h45b05523a2fe135a
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
  30:     0x558ecaa280bc - std::panic::catch_unwind::hd95cea544b2b9bd2
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
  31:     0x558ecaa280bc - std::rt::lang_start_internal::hd16e6ff7bf05a444
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
  32:     0x558ec9c97b2a - std::rt::lang_start::h079fb22616a78fbb
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:165:17
  33:     0x558ec9cc761e - main
  34:     0x7f7cabe18d90 - <unknown>
  35:     0x7f7cabe18e40 - __libc_start_main
  36:     0x558ec9c5cbf5 - _start
  37:                0x0 - <unknown>
make: *** [Makefile:20: integration] Error 101
Error: Process completed with exit code 2.
</pre>
</details>
