### ISSUE TITLE
verify_transaction_and_witness_proof should be consistent with the estimated period

### ISSUE THREAD

**Issue by Xcodes-chain** [nervosnetwork/ckb-cli#562]
verify_transaction_and_witness_proof should be consistent with the estimated period
raw data = False, the call fails and prompts an error
xueyanli@xueyanlideMacBook-Pro ckb-py-integration-test % cat /tmp/tmp.json 
{"block_hash": "0x4c8bc2d0fd4367db1d000417bf64ba06b60daa2ad5f4c7879af0a0804bdc1233", "transactions_proof": {"indices": ["0x0"], "lemmas": []}, "witnesses_proof": {"indices": ["0x0"], "lemmas": []}}%
![image](https://github.com/nervosnetwork/ckb-cli/assets/45781590/2f81075b-7bc4-4aa2-a945-1fc5a2b9ab5b)

**Comment by 15168316096** [comment]
@eval-exec After repairing, synchronize here

**Comment by eval-exec** [comment]
> 

Fixed
