### ISSUE TITLE
Let `ckb-cli deploy sign-txs` write signatures into the info file

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-cli#571]
Since `apply-txs` will read signatures from the info file, it's better that `sign-txs` can write the signatures to the info file directly.

Related to https://github.com/nervosnetwork/ckb-cli/issues/569

Also notice that the output data sturcture of `sign-txs` is not consistent with the cell_tx_signatures schema in the info file.

**Comment by XuJiandong** [comment]
It can be archived by appending " --add-signatures ":
```
ckb-cli deploy sign-txs \
    --add-signatures \
    --info-file info.json
```

**Comment by doitian** [comment]
> It can be archived by appending " --add-signatures ":
> 
> ```
> ckb-cli deploy sign-txs \
>     --add-signatures \
>     --info-file info.json
> ```

It works. Curious why it is not the default option.
