### ISSUE TITLE
Transaction generated by `ckb-cli deploy gen-txs` is rejected

### ISSUE THREAD

**Issue by XuJiandong** [nervosnetwork/ckb-cli#575]
Rejected with following information:
```
[send cell transaction]: 0xe61b097a77057c116116e39a884c79ecd30046b1c90dca8437f68bff8c7da247
Send transaction error: jsonrpc error: `Server error: PoolRejectedTransactionByMinFeeRate: The min fee rate is 1000 shannons/KW, so the transaction fee should be 1591 shannons at least, but only got 1506
```

There is not enough fee after balancing:

https://github.com/nervosnetwork/ckb-cli/blob/c9d814defe063592ed9fdc7986b6fee5753cb462/src/subcommands/deploy/tx_builder.rs#L137

Increasing fee-rate to 1200 can solve this issue.

**Comment by XuJiandong** [comment]
In the multisig scenario, the delta is computed as 1591 - 1506, resulting in 85. Interestingly, this value aligns precisely with the combined size of a pubkey hash (20) and a signature (65). I am contemplating whether there could be an error in the witness calculation for multisig.

**Comment by EthanYuan** [comment]
I simulated twice multisig contract(omnilock) deployments, one new deploy and one upgraded deploy, and both were successful at the default fee-rate of 1000.

- [new deploy tx](https://pudge.explorer.nervos.org/transaction/0xb4cd5d05734446ec94a7e361da579f67d5e3e813eb051f6aab5f6e7ea3eb2663)
- [update depoly tx](https://pudge.explorer.nervos.org/transaction/0x0fd2beaf78d8686ec3ef9421a4edf7647e9df686beae77cf0de5ceb4c1a2b883)
