### ISSUE TITLE
wallet get-capacity --address <address> 命令报 Rocksdb error

### ISSUE THREAD

**Issue by WilliamGuozi** [nervosnetwork/ckb-cli#60]
Rocksdb error: IO error: lock : /root/.ckb-cli/index/0x82b930c957d4f98f8e8214d567a964e3e2814e4a09243eedfe727f/LOCK: No locks available

**Comment by WilliamGuozi** [comment]
```
[  ckb-cli version ]: 0.19.0 (797de91 2019-08-24)
[              url ]: http://127.0.0.1:8224
[              pwd ]: /root
[            color ]: true
[            debug ]: false
[    output format ]: yaml
[ completion style ]: List
[       edit style ]: Emacs
[   index db state ]: Waiting for first query
```

**Comment by doitian** [comment]
You may have already opened the ckb-cli in another console.

**Comment by WilliamGuozi** [comment]
> You may have already opened the ckb-cli in another console.

No, I use the command "ps aux | grep ckb-cli", and can not find the console.

**Comment by TheWaWaR** [comment]
If index is not `synced` you can not use index related sub-command, will improve the user experience later.
