### ISSUE TITLE
When no git information was found, the sub-command `--version` outputs a pair of empty brackets.

### ISSUE THREAD

**Issue by chaoticlonghair** [nervosnetwork/ckb-cli#609]
## Issue

When no git information was found (e.g., no `.git` directory), the sub-command `--version` outputs a pair of empty brackets.

I think the pair of empty brackets should be ignored, when no content between them.

### Current Behavior

Input:

```shell
./ckb-cli --version
```

Output:

```
ckb-cli 1.9.0 ( )
```

### Expected Behavior

Output:

```
ckb-cli 1.9.0
```

**Comment by eval-exec** [comment]
has been fixed by https://github.com/nervosnetwork/ckb-cli/pull/613
