### ISSUE TITLE
git commit information wasn’t injected on build 

### ISSUE THREAD

**Issue by xG0Ian** [nervosnetwork/ckb-cli#612]
## Issue
Run cli from 1.11.0 release `ckb-cli --version` we get:
```
ckb-cli 1.11.0 ( )
```
Which is missing git commit hash.

## Why
I check our history change log of workflows. And found it on pakcage.yaml (newest release version):

```
env:
      BUILDER_IMAGE: nervos/ckb-docker-builder:bionic-rust-1.71.1-openssl-3.1.3
      REL_PKG: x86_64-unknown-linux-gnu.tar.gz
```

Thanks @eval-exec provided tests screenshot on nervosnetwork/ckb#4629

![image](https://github.com/user-attachments/assets/b4283dc4-c53e-4117-83c6-9058881d4af3)

So we run 
```
docker run -it --privileged -v $(pwd):/app -w /app nervos/ckb-docker-builder:bionic-rust-1.71.1-openssl-3.1.3 git describe
```
we got 
```
fatal: detected dubious ownership in repository at '/app'
To add an exception for this directory, call:

        git config --global --add safe.directory /app
```
but we run it on `nervos/ckb-docker-builder:bionic-rust-1.51.0` docker image (which is used on v1.6.0), we got
```
❯ docker run -it --privileged -v $(pwd):/app -w /app nervos/ckb-docker-builder:bionic-rust-1.51.0 git describe
3bc6c51
```

But idk why `ckb` packing use `nervos/ckb-docker-builder:bionic-rust-1.75.0` and works fine.

## FIX
Can fix it by set current workdir to git safe dir. Or can change some env of docker image.

I can submit a PR to fix it by change package.yaml of workflows file, prevent docker image env changed in the future. 

But I think we need to figure out what happens during the `ckb` build when using the same image to ensure it works correctly.

**Comment by xG0Ian** [comment]
I found it on ckb packing action 
![image](https://github.com/user-attachments/assets/1f33acc4-793d-4402-b950-d5791d42bfef)

I believe this is the main reason for the issue.

So we can change `uses: actions/checkout@v2` to `uses: actions/checkout@v3` to fix this issue. Need check for it, bc I can't simulation the github action environments, so idk whether it will work.

We should change this for test:
https://github.com/nervosnetwork/ckb-cli/blob/3bc6c51251a04044f04e74833195f45e774a986a/.github/workflows/package.yaml#L47

Another option which avoid mistake is change this line:
https://github.com/nervosnetwork/ckb-cli/blob/3bc6c51251a04044f04e74833195f45e774a986a/.github/workflows/package.yaml#L58

Add this code to achieve the same effect as actions/checkout@v3.
```
git config --global --add safe.directory /ckb-cli
```

**Comment by eval-exec** [comment]
> We can change `uses: actions/checkout@v2` to `uses: actions/checkout@v3` to fix this issue.

@xG0Ian  Thank you! Please submit a PR to apply this change.

> I can't simulate the GitHub Action environments, so I'm not sure if it will work.

You can add a new workflow job to `.github/workflows/ci.yaml` to build `ckb-cli` and run `ckb-cli --version` to verify that it works.

**Comment by xG0Ian** [comment]
Finally, I find the real reason. The point is:
![image](https://github.com/user-attachments/assets/57698562-9a25-4095-88fd-edfb51791805)
https://github.com/nervosnetwork/ckb-docker-builder/blob/ec0e874c3275d971f274a87921e14766175c9a73/bionic/Dockerfile#L40

we need do some change to fix it:
1. add git safe dir setting to Dockerfile.
2. update the docker image.
3. change `nervos/ckb-docker-builder:bionic-rust-1.71.1-openssl-3.1.3` to new docker image.
```
env:
      BUILDER_IMAGE: nervos/ckb-docker-builder:bionic-rust-1.71.1-openssl-3.1.3
      REL_PKG: x86_64-unknown-linux-gnu.tar.gz
```

we already did this same patch for ckb: https://github.com/nervosnetwork/ckb-docker-builder/commit/b2f33ff54529e58137f5406151478e8119a7eff9 but fotgot ckb-cli

I will submit two PR to change docker image and update the toolchain used on package Action.
